import React from 'react';
import Head from 'next/head';
// import styles from './Home.module.scss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Boiler Plate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {},
  };
}
